### ISSUE TITLE
The About page is too long and cumbersome

### ISSUE THREAD

**Issue by jmacdotorg** [Five-Borough-Fedi-Project/Five-Borough-Fedi-Project.github.io#4]
We have a very rich and structured "About" section at https://masto.nyc/about, listing out various policies, resources, and links. While we should make this information easy to find, I don't think that this is the best location for it. I propose that we move this information to a static site, and replace the content of this section with something quite short.

The Mastodon-generated About page has a standard layout, vertically stacking server branding, admin information, About text, a Rules list, and a blocked-servers list. There is no table of contents on the page. The contents of the sections are loaded in via JavaScript, meaning that you can't hyperlink to any individual sections. This makes it hard to link directly to any specific rule or policy, or even to the list of server rules in general.

I get the distinct impression that Mastodon intends you to not to provide a whole webpage like we have as the contents for "About", but more to "customize" it with a little bit of information about your server. More on the scale of an account bio than a full CV, in other words.

Now that we have a real website in the form on 5bfp.org, I think we should lift and shift this About text into a real, static webpage, and leave behind more of a blurb with the most basic server identity followed by links for more information.

**Comment by jmacdotorg** [comment]
In addition to adding the web page proposed by #5, I propose replacing the About section at https://masto.nyc/about with [the text on this Google doc](https://docs.google.com/document/d/1QpR5MfZOSvNrIsCi5X4xhkUTKDpgIusJ7SQbuF6VhNg/edit?usp=sharing).

**Comment by jmacdotorg** [comment]
@seano-vs Thanks for merging #5! At convenience please review the proposal to replace the /About text, as well.

**Comment by seano-vs** [comment]
Added a few tiny additions, otherwise this looks great

**Comment by seano-vs** [comment]
LGTM 👍
